/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "byzantine.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

responseMessage *
sendmessage_1(requestMessage *argp, CLIENT *clnt)
{
	static responseMessage clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, SENDMESSAGE,
		(xdrproc_t) xdr_requestMessage, (caddr_t) argp,
		(xdrproc_t) xdr_responseMessage, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
