/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "byzantine.h"

bool_t
xdr_requestMessage (XDR *xdrs, requestMessage *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->message))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->srcId))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->destId))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_responseMessage (XDR *xdrs, responseMessage *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->message))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->srcId))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->destId))
		 return FALSE;
	return TRUE;
}
