/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "stdio.h"
#include "dictionary.h"

int * insert_1_svc(dictionary *argp, struct svc_req *rqstp)
{
	static int result;

	printf("Vaibhav1\n");

	return &result;
}

dictionary * lookup_1_svc(char **argp, struct svc_req *rqstp)
{
	static dictionary  result;

	/*
	 * insert server code here
	 */

	return &result;
}

char ** deleteword_1_svc(char **argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return &result;
}
