/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "dictionary.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

resultlong *
insert_1(dictionary *argp, CLIENT *clnt)
{
	static resultlong clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, INSERT,
		(xdrproc_t) xdr_dictionary, (caddr_t) argp,
		(xdrproc_t) xdr_resultlong, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

lookupword *
lookup_1(dictionary *argp, CLIENT *clnt)
{
	static lookupword clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, LOOKUP,
		(xdrproc_t) xdr_dictionary, (caddr_t) argp,
		(xdrproc_t) xdr_lookupword, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

resultlong *
deleteword_1(dictionary *argp, CLIENT *clnt)
{
	static resultlong clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, DELETEWORD,
		(xdrproc_t) xdr_dictionary, (caddr_t) argp,
		(xdrproc_t) xdr_resultlong, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
