/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "dictionary.h"

bool_t
xdr_dictionary (XDR *xdrs, dictionary *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->word, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->meaning, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lookupword (XDR *xdrs, lookupword *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->word, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->meaning, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_resultlong (XDR *xdrs, resultlong *objp)
{
	register int32_t *buf;

	 if (!xdr_long (xdrs, &objp->success))
		 return FALSE;
	return TRUE;
}
