/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _DICTIONARY_H_RPCGEN
#define _DICTIONARY_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct dictionary {
	char *word;
	char *meaning;
};
typedef struct dictionary dictionary;

struct lookupword {
	char *word;
	char *meaning;
};
typedef struct lookupword lookupword;

struct resultlong {
	long success;
};
typedef struct resultlong resultlong;

#define DICTIONARY_PROG 0x31240000
#define DICTIONARY_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define INSERT 1
extern  resultlong * insert_1(dictionary *, CLIENT *);
extern  resultlong * insert_1_svc(dictionary *, struct svc_req *);
#define LOOKUP 2
extern  lookupword * lookup_1(dictionary *, CLIENT *);
extern  lookupword * lookup_1_svc(dictionary *, struct svc_req *);
#define DELETEWORD 3
extern  resultlong * deleteword_1(dictionary *, CLIENT *);
extern  resultlong * deleteword_1_svc(dictionary *, struct svc_req *);
extern int dictionary_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define INSERT 1
extern  resultlong * insert_1();
extern  resultlong * insert_1_svc();
#define LOOKUP 2
extern  lookupword * lookup_1();
extern  lookupword * lookup_1_svc();
#define DELETEWORD 3
extern  resultlong * deleteword_1();
extern  resultlong * deleteword_1_svc();
extern int dictionary_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_dictionary (XDR *, dictionary*);
extern  bool_t xdr_lookupword (XDR *, lookupword*);
extern  bool_t xdr_resultlong (XDR *, resultlong*);

#else /* K&R C */
extern bool_t xdr_dictionary ();
extern bool_t xdr_lookupword ();
extern bool_t xdr_resultlong ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_DICTIONARY_H_RPCGEN */
