/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "dictionary.h"


void
dictionary_prog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	dictionary  insert_1_arg;
	dictionary  *result_2;
	char * lookup_1_arg;
	char * *result_3;
	char * deleteword_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, DICTIONARY_PROG, DICTIONARY_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	insert_1_arg.word = "hi";
	insert_1_arg.meaning = "hello";
	printf("Vaibhav1\n");
	result_1 = insert_1(&insert_1_arg, clnt);
	printf("Vaibhav2\n");
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	dictionary_prog_1 (host);
exit (0);
}
